# Generated by Django 3.2 on 2022-07-19 09:40

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/alexacraman/Business/MentalHealthAware/protected')), upload_to='protected'),
        ),
    ]
